### ISSUE TITLE
Problemas sequencial

### ISSUE THREAD

**Issue by pilla** [DaiaAndrade/trabalho-1-tabela-hash-concorrente-teamtoto-master#1]
./main
Teste ate 10 OK
Chave: 2. Conteúdo: 140672405353232
main(48590,0x7fff7b227000) malloc: *** error for object 0x7ff0d8c03320: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

**Comment by DaiaAndrade** [comment]
Professor, eu mudei meu main para que fizesse basicamente o mesmo que o seu caso de testes:
Insere números de 0-9
Busca chaves pares
Busca conteúdos ímpares
Remove Conteúdos Pares
Insere conteúdo pra colisão

Meu problema com seu caso de teste em geral:
linha 18: ht_busca_conteudo(ht, &u) - o senhor passa um endereço qualquer como conteúdo pra ser buscado dentro da hash. Esse endereço tipicamente não vai estar na hash. Eu imprimia esse &u e verificava se estava na hash, e ele nunca estava. Esse mesmo problema se encontra em verifica_impares(linhas 28 e 32) e verifica_impares_colisoes(linhas 43 e 47). Não sei se isso foi proposital do senhor, pra falhar mesmo, mas me deixou confusa. Retirei o & e estava tudo normal

linha 58: assert(==NULL) - Esse eu acho que foi proposital. Está aqui apenas porque me apresentou erro, depois que eu comentei o programa continuou

linha 68: *conteudo = i; - Esse me deixou confusa. Quando eu imprimia a sua hash, ela mostrava endereços na inserção. Se eu tirasse o * da atribuição, ele inseria o valor de 0-9, que eu imagino como o esperado, do contrário não, inserindo endereços. Eu fiquei bem confusa sobre se isso era intencional ou não. 

Esse tipo de coisa se propagou dentro do meu programa para a remoção a partir da linha 81. Quando eu passei a remover os * tudo voltada ao normal. E na linha 88, aquele free, por algum motivo, me dava erro. Eu comentei ele no seu código, e funcionava.

linha 98: inserção de colisões
Eu não sei se sou eu que desconhecia isso ou o que, mas quando fazes, na linha 103: cont = cont+10 o i (que eram números ímpares), ficavam com 90 valores a mais. Não sei se é a base do unsigned long int ou o que, mas achei o comportamento... estranho. E quando adicionamos 1, ele adiciona 10 valores. Não se se entendi direito a funcionalidade, mas entendo que era pra gerar colisões. O único problema é que meu tratamento de colisões é colocar qualquer colisão em uma lista encadeada naquela chave. Então checar a colisão, no meu caso, sempre vai dar erro, se eu entendi direito seus testes (coisa que admito, só entendi o verifica_0_9).

Teoricamente, considerando tudo o que eu escrevi, e arrumando o que me dava erro nos testes e o erro de alocação, o programa está funcionando. Se o senhor olhar meu main.c, ele apresenta testes similares aos seus, porém mais simples. E está funcionando. Não tenho certeza se funcionará com o senhor, mas se precisares da versão de testes que modifiquei por conta das observações acima, ela está no repositório, é o arquivo main_testes.c

Obrigada
